'use client';
import {useEffect,useRef,useState} from 'react';
import {clients,expertise,journey,products,profile,type Project,technologyGroups,workflow} from '../data/content';
const nav=[['overview','Overview'],['about','About'],['expertise','Expertise'],['products','Products'],['client-work','Client Work'],['journey','Journey'],['contact','Contact']];
const socials=[{label:'LinkedIn',url:profile.linkedin},{label:'GitHub',url:profile.github},{label:'Email',url:profile.email?`mailto:${profile.email}`:''}];
function LinkOrPlaceholder({href,children,className=''}:{href:string;children:React.ReactNode;className?:string}){if(!href)return <span className={`${className} unavailable`} title="Link to be configured" aria-disabled="true">{children}</span>;return <a className={className} href={href} target={href.startsWith('http')?'_blank':undefined} rel="noreferrer">{children}</a>}
function ProjectCard({project,index,onOpen}:{project:Project;index:number;onOpen:(p:Project)=>void}){return <button className="project-card reveal" style={{'--accent':project.accent,'--delay':`${index*70}ms`} as React.CSSProperties} onClick={()=>onOpen(project)} aria-label={`View ${project.name} details`}><div className="poster-art"><span className="poster-grid"/><b>{project.monogram}</b><i>{String(index+1).padStart(2,'0')}</i></div><div className="card-copy"><div><p>{project.category}</p><h3>{project.name}</h3></div><span>↗</span></div><p className="card-description">{project.description}</p>{project.private&&<small>⌁ &nbsp; Private commercial product</small>}</button>}
export function Portfolio(){const[menu,setMenu]=useState(false),[selected,setSelected]=useState<Project|null>(null),[intro,setIntro]=useState(true);const productRow=useRef<HTMLDivElement>(null);useEffect(()=>{const seen=sessionStorage.getItem('geetz-intro');const timer=setTimeout(()=>{setIntro(false);sessionStorage.setItem('geetz-intro','1')},seen?250:2100);return()=>clearTimeout(timer)},[]);useEffect(()=>{const nodes=document.querySelectorAll('.reveal');const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});nodes.forEach(n=>observer.observe(n));return()=>observer.disconnect()},[]);useEffect(()=>{document.body.style.overflow=selected||menu?'hidden':'';return()=>{document.body.style.overflow=''}},[selected,menu]);const move=(dir:number)=>productRow.current?.scrollBy({left:dir*390,behavior:'smooth'});return <>
<div className={`preloader ${intro?'':'preloader-out'}`} aria-hidden={!intro}><div className="intro-word"><span>G</span><i>EETZ</i></div><p>Software Engineer · AI Product Builder</p></div>
<header className="nav"><a className="brand" href="#overview" aria-label="GEETZ home">G<span>EE</span>TZ</a><nav className="nav-links" aria-label="Primary navigation">{nav.map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav><div className="nav-end"><LinkOrPlaceholder className="resume-link" href={profile.resume}>Résumé ↓</LinkOrPlaceholder><button className="menu-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}><i/><i/></button></div></header>
<div className={`mobile-menu ${menu?'open':''}`}>{nav.map(([id,label],i)=><a key={id} onClick={()=>setMenu(false)} href={`#${id}`}><span>0{i+1}</span>{label}</a>)}</div>
<main><section id="overview" className="hero section"><div className="hero-glow"/><div className="grid-plane"/><div className="hero-copy"><p className="eyebrow"><span/>Founder · Software Engineer · AI Product Builder</p><h1>Ideas, engineered<br/>into <em>impact.</em></h1><p className="intro">I&apos;m <strong>Geetha K S</strong>, founder of Kripra&apos;s Digital AI. I build AI-powered products, enterprise platforms, and custom digital solutions from concept to production.</p><div className="actions"><a className="button primary" href="#products">Explore my work <span>↓</span></a><a className="button secondary" href="#contact">Let&apos;s connect <span>↗</span></a></div><div className="availability"><i/> Building purposeful technology from India <span>—</span> available globally</div></div><div className="hero-mark" aria-hidden="true"><div className="orb"><span>G</span></div><p>GEETZ / 2026</p></div><div className="scroll-cue"><span>Scroll to explore</span><i/></div></section>
<section id="about" className="section about"><div className="section-label reveal"><span>01</span> About</div><div className="about-layout"><h2 className="reveal">Founder mindset.<br/><em>Engineer&apos;s discipline.</em></h2><div className="about-copy reveal"><p>I turn ideas and business requirements into thoughtful software products—working across product thinking, architecture, engineering, and delivery.</p><p>My focus spans AI-enabled applications, full-stack development, enterprise platforms, SaaS, and workflow digitisation. The work is practical, intentional, and built for the real world.</p><div className="signature">GEETZ <span>Building from concept to production</span></div></div></div></section>
<section id="expertise" className="section expertise"><div className="section-label reveal"><span>02</span> What I build</div><div className="section-heading reveal"><h2>Engineering, end to end.</h2><p>From first requirements to production-ready systems.</p></div><div className="expertise-grid">{expertise.map(([n,title,text])=><article className="expertise-card reveal" key={n}><span>{n}</span><div className="expertise-icon">⌁</div><h3>{title}</h3><p>{text}</p><i>↗</i></article>)}</div></section>
<section id="products" className="section products"><div className="section-label reveal"><span>03</span> Featured products</div><div className="section-heading row reveal"><div><h2>Products with purpose.</h2><p>Selected commercial work, described with confidentiality intact.</p></div><div className="row-controls"><button onClick={()=>move(-1)} aria-label="Scroll products left">←</button><button onClick={()=>move(1)} aria-label="Scroll products right">→</button></div></div><div className="project-row" ref={productRow}>{products.map((p,i)=><ProjectCard key={p.name} project={p} index={i} onOpen={setSelected}/>)}</div></section>
<section id="client-work" className="section clients"><div className="section-label reveal"><span>04</span> Client work</div><div className="section-heading reveal"><h2>Built in partnership.</h2><p>Professional technology engagements, kept intentionally high-level.</p></div><div className="client-grid">{clients.map((client,i)=><button key={client.name} className="client-card reveal" onClick={()=>setSelected(client)}><span className="client-no">0{i+1}</span><div className="client-mark">{client.monogram}</div><div><p>{client.category}</p><h3>{client.name}</h3><small>Project details kept confidential</small></div><i>↗</i></button>)}</div></section>
<section id="stack" className="section stack"><div className="section-label reveal"><span>05</span> Engineering stack</div><div className="section-heading reveal"><h2>Tools follow the problem.</h2><p>Verified technologies can be added here without changing the design.</p></div><div className="stack-grid">{technologyGroups.map((g,i)=><div className="stack-card reveal" key={g.name}><span>0{i+1}</span><h3>{g.name}</h3><p>{g.items.length?g.items.join(' · '):'Technology list awaiting verification'}</p></div>)}</div></section>
<section id="process" className="section process"><div className="section-label reveal"><span>06</span> How I build</div><div className="section-heading reveal"><h2>From signal to software.</h2></div><div className="workflow">{workflow.map((step,i)=><div className="workflow-step reveal" key={step}><span>{String(i+1).padStart(2,'0')}</span><b>{step}</b>{i<workflow.length-1&&<i>→</i>}</div>)}</div></section>
<section id="journey" className="section journey"><div className="section-label reveal"><span>07</span> Professional journey</div><div className="journey-layout"><h2 className="reveal">Building forward,<br/><em>one layer at a time.</em></h2><div className="timeline">{journey.map((item,i)=><div className="timeline-item reveal" key={item}><span>{String(i+1).padStart(2,'0')}</span><h3>{item}</h3><i/></div>)}</div></div></section>
<section id="company" className="section company"><div className="company-card reveal"><div><p>Company / Founder</p><h2>Kripra&apos;s<br/>Digital AI</h2></div><div><p>A technology company focused on building thoughtful AI and software solutions for modern businesses.</p><LinkOrPlaceholder className="text-link" href={profile.companyWebsite}>Visit company website <span>↗</span></LinkOrPlaceholder></div><b aria-hidden="true">K</b></div></section>
<section id="github" className="section github"><div className="github-card reveal"><div className="code-mark">&lt;/&gt;</div><div><p>Engineering / GitHub</p><h2>Built openly.<br/><em>Protected responsibly.</em></h2><span>Selected commercial products are maintained in private repositories to protect proprietary technology and client confidentiality.</span></div><LinkOrPlaceholder className="round-link" href={profile.github}>View GitHub ↗</LinkOrPlaceholder></div></section>
<section id="contact" className="section contact"><div className="contact-orb"/><p className="eyebrow reveal"><span/>Start a conversation</p><h2 className="reveal">Have an idea<br/><em>worth building?</em></h2><p className="reveal">Let&apos;s turn ambitious ideas into thoughtful, scalable digital products.</p><div className="contact-links reveal">{socials.map(s=><LinkOrPlaceholder key={s.label} href={s.url}>{s.label} <span>↗</span></LinkOrPlaceholder>)}<LinkOrPlaceholder href={profile.companyWebsite}>Kripra&apos;s Digital AI <span>↗</span></LinkOrPlaceholder></div></section></main>
<footer><a className="brand" href="#overview">G<span>EE</span>TZ</a><p>Founder · Software Engineer · AI Product Builder</p><div>{socials.map(s=><LinkOrPlaceholder key={s.label} href={s.url}>{s.label}</LinkOrPlaceholder>)}</div><small>© {new Date().getFullYear()} Geetha K S</small></footer>
{selected&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setSelected(null)}><article className="project-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={e=>e.stopPropagation()} style={{'--accent':selected.accent} as React.CSSProperties}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close project details">×</button><div className="modal-art"><b>{selected.monogram}</b><span>{selected.category}</span></div><div className="modal-content"><p>{selected.private?'Private commercial product':'Client project'}</p><h2 id="modal-title">{selected.name}</h2><div className="modal-grid"><div><span>Overview</span><p>{selected.description}</p></div><div><span>My role</span><p>{selected.role}</p></div><div><span>Technology</span><p>{selected.technologies.length?selected.technologies.join(', '):'Not publicly specified'}</p></div><div><span>Status</span><p>{selected.status}</p></div></div></div></article></div>}</>}
